name: Tests build

on:
  push:
    branches:
      - 4418_test_update_import_test

env:
  DVC_TEST: "true"
  HOMEBREW_NO_AUTO_UPDATE: 1
  SHELL: /bin/bash

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        pyv: [3.6, 3.7, 3.8]
        exclude:
          - os: windows-2019
            pyv: 3.8
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python
      uses: actions/setup-python@v2.1.2
      with:
        python-version: ${{ matrix.pyv }}
    - name: install
      run: |
        pip install ".[all,tests]"
    - name: setup git
      run: |
        git config --global user.email "dvctester@example.com"
        git config --global user.name "DVC Tester"
    - name: run tests
      run: python -m tests -n=1 "tests/func/test_update.py::test_update_import[False]"


